[package]
name = "sermonizer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.29"
ctrlc = "3.4"
ratatui = "0.29"
serialport = "4.3"
tokio = { version = "1.0", features = ["full"] }
